services:
  frontend:
    image: nginx:alpine
    container_name: graduation-frontend
    ports:
      - "8321:80"
    networks:
      - graduation-network
    volumes:
      - /home/k611/data3/lys/product/frontend-1/dist:/usr/share/nginx/html
      - /home/k611/data3/lys/product/frontend-1/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    image: graduation-backend-triplanenet
    container_name: graduation-backend-triplanenet
    networks:
      - graduation-network
    # 根据您的后端需求添加必要的配置
    # ports:
    #   - "8001:8001"
    # volumes:
    #   - ./backend-data:/app/data

networks:
  graduation-network:
    driver: bridge 